### ISSUE TITLE
Crash parsing segmentation_descriptor data

### ISSUE THREAD

**Issue by dholroyd** [m2amedia/scte35dump#4]
```
SpliceInfoHeader { protocol_version: 0, encrypted_packet: false, encryption_algorithm: None, pts_adjustment: 6913847087, cw_index: 0, tier: 4095 } TimeSignal {
    splice_time: Timed(
        Some(
            1683572058,
        ),
    ),
}
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `144`,
 right: `152`', /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/scte35-reader-0.6.0/src/lib.rs:536:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Link for sample file for analysis > http://www.mediafire.com/file/35mlgowmq10x16a/time_signal.ts/file

_Originally posted by @ashoktk11 in https://github.com/m2amedia/scte35dump/issues/1#issuecomment-512887231_

**Comment by dholroyd** [comment]
This is an additional example where the underlying cause is per https://github.com/dholroyd/scte35-reader/issues/3.

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `144`,
 right: `152`', /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/scte35-reader-0.10.0/src/lib.rs:646:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: scte35_reader::SpliceDescriptor::parse_segmentation_descriptor
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/scte35-reader-0.10.0/src/lib.rs:646
   8: scte35_reader::SpliceDescriptor::parse
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/scte35-reader-0.10.0/src/lib.rs:697
   9: <scte35_reader::SpliceDescriptorIter as core::iter::traits::iterator::Iterator>::next
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/scte35-reader-0.10.0/src/lib.rs:810
  10: <scte35dump::mpegts::DumpSpliceInfoProcessor as scte35_reader::SpliceInfoProcessor>::process
             at src/mpegts.rs:44
  11: <scte35_reader::Scte35SectionProcessor<P,Ctx> as mpeg2ts_reader::psi::WholeCompactSyntaxPayloadParser>::section
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/scte35-reader-0.10.0/src/lib.rs:884
  12: scte35dump::section_main
             at src/main.rs:43
  13: scte35dump::main
             at src/main.rs:58
  14: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  18: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by dholroyd** [comment]
@ashoktk11 please reinstall to get the latest 0.1.6 release and try again.  Your example file is now working for me.

e.g.
```
Program Pid(0100): Found SCTE-35 data on Pid(01ba) (0x1ba)                                                                                                                                                         
Last PCR{0065128c:0005}: SpliceInfoHeader { protocol_version: 0, encrypted_packet: false, encryption_algorithm: None, pts_adjustment: 6913847087, cw_index: 0, tier: 4095 } TimeSignal {                           
    splice_time: Timed(                                                                                                                                                                                            
        Some(                                                                                                                                                                                                      
            1683572058,                                                                                                                                                                                            
        ),                                                                                                                                                                                                         
    ),                                                                                                                                                                                                             
}                                                                                                                                                                                                                  
 - Ok(SegmentationDescriptor { segmentation_event_id: 1003748049, descriptor_detail: Insert { program_segmentation_flag: true, segmentation_duration_flag: false, delivery_not_restricted_flag: true, delivery_restrictions: None, segmentation_mode: Program, segmentation_duration: None, segmentation_upid_type: TI, segmentation_upid_length: 8, segmentation_upid: SegmentationUpid { upid: [0, 0, 0, 0, 7, 33, 206, 252] }, segmentation_type_id: ChapterEnd, segment_num: 1, segments_expected: 1, sub_segment_num: 0, sub_segments_expected: 0 } })                                                                                             
 - Ok(SegmentationDescriptor { segmentation_event_id: 1004518241, descriptor_detail: Insert { program_segmentation_flag: true, segmentation_duration_flag: true, delivery_not_restricted_flag: true, delivery_restrictions: None, segmentation_mode: Program, segmentation_duration: Some(900000), segmentation_upid_type: TI, segmentation_upid_length: 8, segmentation_upid: SegmentationUpid { upid: [0, 0, 1, 22, 152, 165, 92, 89] }, segmentation_type_id: BreakStart, segment_num: 1, segments_expected: 1, sub_segment_num: 0, sub_segments_expected: 0 } })                                                                                    
 - Ok(SegmentationDescriptor { segmentation_event_id: 1004518231, descriptor_detail: Insert { program_segmentation_flag: true, segmentation_duration_flag: true, delivery_not_restricted_flag: true, delivery_restrictions: None, segmentation_mode: Program, segmentation_duration: Some(450000), segmentation_upid_type: TI, segmentation_upid_length: 8, segmentation_upid: SegmentationUpid { upid: [0, 0, 0, 0, 7, 34, 128, 92] }, segmentation_type_id: ProviderAdvertisementStart, segment_num: 1, segments_expected: 2, sub_segment_num: 0, sub_segments_expected: 0 } })                                                                       
 - Ok(SegmentationDescriptor { segmentation_event_id: 1004518286, descriptor_detail: Insert { program_segmentation_flag: true, segmentation_duration_flag: false, delivery_not_restricted_flag: true, delivery_restrictions: None, segmentation_mode: Program, segmentation_duration: None, segmentation_upid_type: MPU, segmentation_upid_length: 27, segmentation_upid: SegmentationUpid { upid: [82, 84, 76, 78, 49, 72, 1, 0, 0, 0, 0, 49, 49, 49, 57, 48, 49, 49, 49, 56, 48, 56, 52, 53, 65, 49, 0] }, segmentation_type_id: ContentIdentification, segment_num: 0, segments_expected: 0, sub_segment_num: 0, sub_segments_expected: 0 } })       
```

**Comment by ashoktk11** [comment]
> @ashoktk11 please reinstall to get the latest 0.1.6 release and try again. Your example file is now working for me.
> 
> e.g.
> 
> ```
> Program Pid(0100): Found SCTE-35 data on Pid(01ba) (0x1ba)                                                                                                                                                         
> Last PCR{0065128c:0005}: SpliceInfoHeader { protocol_version: 0, encrypted_packet: false, encryption_algorithm: None, pts_adjustment: 6913847087, cw_index: 0, tier: 4095 } TimeSignal {                           
>     splice_time: Timed(                                                                                                                                                                                            
>         Some(                                                                                                                                                                                                      
>             1683572058,                                                                                                                                                                                            
>         ),                                                                                                                                                                                                         
>     ),                                                                                                                                                                                                             
> }                                                                                                                                                                                                                  
>  - Ok(SegmentationDescriptor { segmentation_event_id: 1003748049, descriptor_detail: Insert { program_segmentation_flag: true, segmentation_duration_flag: false, delivery_not_restricted_flag: true, delivery_restrictions: None, segmentation_mode: Program, segmentation_duration: None, segmentation_upid_type: TI, segmentation_upid_length: 8, segmentation_upid: SegmentationUpid { upid: [0, 0, 0, 0, 7, 33, 206, 252] }, segmentation_type_id: ChapterEnd, segment_num: 1, segments_expected: 1, sub_segment_num: 0, sub_segments_expected: 0 } })                                                                                             
>  - Ok(SegmentationDescriptor { segmentation_event_id: 1004518241, descriptor_detail: Insert { program_segmentation_flag: true, segmentation_duration_flag: true, delivery_not_restricted_flag: true, delivery_restrictions: None, segmentation_mode: Program, segmentation_duration: Some(900000), segmentation_upid_type: TI, segmentation_upid_length: 8, segmentation_upid: SegmentationUpid { upid: [0, 0, 1, 22, 152, 165, 92, 89] }, segmentation_type_id: BreakStart, segment_num: 1, segments_expected: 1, sub_segment_num: 0, sub_segments_expected: 0 } })                                                                                    
>  - Ok(SegmentationDescriptor { segmentation_event_id: 1004518231, descriptor_detail: Insert { program_segmentation_flag: true, segmentation_duration_flag: true, delivery_not_restricted_flag: true, delivery_restrictions: None, segmentation_mode: Program, segmentation_duration: Some(450000), segmentation_upid_type: TI, segmentation_upid_length: 8, segmentation_upid: SegmentationUpid { upid: [0, 0, 0, 0, 7, 34, 128, 92] }, segmentation_type_id: ProviderAdvertisementStart, segment_num: 1, segments_expected: 2, sub_segment_num: 0, sub_segments_expected: 0 } })                                                                       
>  - Ok(SegmentationDescriptor { segmentation_event_id: 1004518286, descriptor_detail: Insert { program_segmentation_flag: true, segmentation_duration_flag: false, delivery_not_restricted_flag: true, delivery_restrictions: None, segmentation_mode: Program, segmentation_duration: None, segmentation_upid_type: MPU, segmentation_upid_length: 27, segmentation_upid: SegmentationUpid { upid: [82, 84, 76, 78, 49, 72, 1, 0, 0, 0, 0, 49, 49, 49, 57, 48, 49, 49, 49, 56, 48, 56, 52, 53, 65, 49, 0] }, segmentation_type_id: ContentIdentification, segment_num: 0, segments_expected: 0, sub_segment_num: 0, sub_segments_expected: 0 } })       
> ```

Thanks a lot dholroyd, It's working for me now
