### ISSUE TITLE
thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by ansariatif** [m2amedia/scte35dump#42]
i face this iuse "thread 'main' has overflowed its stack"

  clap v2.34.0 this clap version

**Comment by dholroyd** [comment]
clap is now bumped to 3.2.8 in `master` - does that help?

If not, share more diagnostic info about the failure.

**Comment by turbidwater** [comment]
@dholroyd could you please output a new release that has this package bumped? I installed scte35dump today using `cargo install scte35dump` and it still is on version 0.1.6, which is using clap 2.34.0 still. It looks like that 0.1.6 release was made long before the upgrade of clap to 3.2.8. 

In short, on Windows after a fresh install, running `scte35dump --help` results in the response `thread 'main' has overflowed its stack`.

**Comment by dholroyd** [comment]
@turbidwater I've bumped several dependencies to even more recent releases and pushed version [0.1.7](https://crates.io/crates/scte35dump/0.1.7).  Please give it a spin!

**Comment by turbidwater** [comment]
@dholroyd Thanks for the new build. Unfortunately it still throws the same error:
```
Compiling base64 v0.21.7
   Compiling scte35-reader v0.14.0
   Compiling scte35dump v0.1.7
    Finished release [optimized] target(s) in 51.97s
warning: the following packages contain code that will be rejected by a future version of Rust: syn v0.14.9
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
  Installing C:\Users\nthin\.cargo\bin\scte35dump.exe
   Installed package `scte35dump v0.1.7` (executable `scte35dump.exe`)
PS C:\_projects\assets\SCTE Samples> scte35dump --help

thread 'main' has overflowed its stack
```

If it helps, I'm running 
```
rustc --version
rustc 1.76.0 (07dca489a 2024-02-04)
```
And I'm trying in git bash and powershell on Windows.

**Comment by dholroyd** [comment]
Looks like this problem with clap will need more investigation.

In the meantime, please can you try building an exe with a larger default stack as a workaround?

I was able to reproduce this problem in a VM, and was able to work around it with the following steps,

```
set RUSTFLAGS=-C link-arg=/STACK:8000000

cargo install --force scte35dump
```

**Comment by turbidwater** [comment]
@dholroyd Thanks for the suggestion. Unfortunately, it's the same result. I uninstalled scte35dump, ran the rust flag command and did the force install and I ended up with the same output.

**Comment by dholroyd** [comment]
I tried switching from clap to another cli arg parser, but I still get a crash when run in a windows VM using default compilation options.

Maybe you could try my previous suggestion again, but further increasing the default stack size for the resulting exe to 16MB,

```
set RUSTFLAGS=-C link-arg=/STACK:16000000
```

**Comment by turbidwater** [comment]
@dholroyd Sorry, reinstalling with that stack size didn't change the output. I should note that I'm not trying to do this in my own program. I'm only doing this in the CLI. I'm ignorant of how Rust works, so I don't know if that makes a difference.

**Comment by dholroyd** [comment]
Please could you try installing the latest code directly from github,

```
cargo install --force --git https://github.com/m2amedia/scte35dump.git
```

I made a small change that I hope may address the issue.

**Comment by turbidwater** [comment]
@dholroyd Hey, that worked! Thanks! I was able to run help and then run the command and get the SCTE out of the target file. Thanks for working through that!

**Comment by dholroyd** [comment]
For the record, the problem was nothing to do with the clap library.

One of the functions in the code was using a large stack-based buffer, and I assume the rust compiler would in some circumstances decide to inline that function into `main()`, meaning that `main()` would need a very large stack frame even if the function in question wasn't called at runtime.

**Comment by dholroyd** [comment]
There is now a new 0.1.8 release that contains this fix plus a couple of updates to newer dependency versions.
