### ISSUE TITLE
How to use udp options

### ISSUE THREAD

**Issue by cisiwen** [m2amedia/scte35dump#72]
Hi

i am new to scte35 believe scte35dump is the tool i am looking for my work
we don't have rtp source but we have udp, seem the --udp option need use 
to get it working but when i try

` scte35dump net -m 224.2.2.4 -p 1234  --udp  --ifaddr 192.168.1.100`

i got
`error: Found argument '--udp' which wasn't expected, or isn't valid in this context`

any ideas how to use this tool for udp streams

thanks

Winston

**Comment by dholroyd** [comment]
Probably the problem was that at the time the released version of the tool didn't yet contain the `--udp` option.  I've just pushed a new release so you should try again :crossed_fingers:
